/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Red Shield Founding Driver Program API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
  message?: string;
}

export interface MessageResponse {
  message: string;
}

export interface RegisterDriverRequest {
  fullName: string;
  email: string;
  /** @minLength 6 */
  password: string;
  phone: string;
  city: string;
  state: string;
  vehicleType: string;
  yearsExperience: number;
  referralCode?: string;
  agreedToTerms: boolean;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export type UserProfileRole =
  (typeof UserProfileRole)[keyof typeof UserProfileRole];

export const UserProfileRole = {
  admin: "admin",
  driver: "driver",
} as const;

export type UserProfileApplicationStatus =
  (typeof UserProfileApplicationStatus)[keyof typeof UserProfileApplicationStatus];

export const UserProfileApplicationStatus = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
} as const;

export type UserProfilePaymentStatus =
  (typeof UserProfilePaymentStatus)[keyof typeof UserProfilePaymentStatus];

export const UserProfilePaymentStatus = {
  unpaid: "unpaid",
  paid: "paid",
} as const;

export type UserProfileProductPurchased =
  (typeof UserProfileProductPurchased)[keyof typeof UserProfileProductPurchased] | null;

export const UserProfileProductPurchased = {
  training: "training",
  membership: "membership",
  bundle: "bundle",
} as const;

export type UserProfileMembershipTier =
  (typeof UserProfileMembershipTier)[keyof typeof UserProfileMembershipTier];

export const UserProfileMembershipTier = {
  starter: "starter",
  builder: "builder",
  elite: "elite",
} as const;

export interface UserProfile {
  id: number;
  role: UserProfileRole;
  fullName: string;
  email: string;
  phone?: string;
  city?: string;
  state?: string;
  vehicleType?: string;
  yearsExperience?: number;
  referralCode: string;
  applicationStatus: UserProfileApplicationStatus;
  paymentStatus: UserProfilePaymentStatus;
  /** Which product this user purchased. Null until payment is completed. */
  productPurchased: UserProfileProductPurchased;
  /** Current membership tier. Defaults to 'starter'. */
  membershipTier: UserProfileMembershipTier;
  /** Whether this user joined during the founding driver window. */
  isFoundingMember: boolean;
  /** Affiliate program code. Null until the user enrolls in the affiliate program. */
  affiliateCode: string | null;
  createdAt: string;
}

export interface AuthResponse {
  user: UserProfile;
  message: string;
}

export interface CheckoutSessionResponse {
  sessionId: string;
  url: string;
}

export type PaymentStatusResponsePaymentStatus =
  (typeof PaymentStatusResponsePaymentStatus)[keyof typeof PaymentStatusResponsePaymentStatus];

export const PaymentStatusResponsePaymentStatus = {
  unpaid: "unpaid",
  paid: "paid",
} as const;

export interface PaymentRecord {
  id: number;
  amount: number;
  currency: string;
  status: string;
  paidAt?: string;
  createdAt: string;
}

export interface PaymentStatusResponse {
  paymentStatus: PaymentStatusResponsePaymentStatus;
  payment?: PaymentRecord;
}

export type ReferralRecordRewardStatus =
  (typeof ReferralRecordRewardStatus)[keyof typeof ReferralRecordRewardStatus];

export const ReferralRecordRewardStatus = {
  pending: "pending",
  paid: "paid",
} as const;

export interface ReferralRecord {
  id: number;
  referredUserName: string;
  referredUserEmail?: string;
  referralNumber: number;
  rewardAmount: number;
  rewardStatus: ReferralRecordRewardStatus;
  qualifiedAt?: string;
  paidAt?: string;
  createdAt: string;
}

export interface DriverDashboard {
  driver: UserProfile;
  referralLink: string;
  totalReferrals: number;
  pendingRewardsTotal: number;
  paidRewardsTotal: number;
  currentTier: string;
  nextTierMessage: string;
  referrals: ReferralRecord[];
}

export interface AdminStats {
  totalDrivers: number;
  paidDrivers: number;
  unpaidApplicants: number;
  totalReferrals: number;
  pendingPayouts: number;
  paidPayouts: number;
}

export interface AdminDriverSummary {
  id: number;
  fullName: string;
  email: string;
  phone?: string;
  city?: string;
  state?: string;
  vehicleType?: string;
  referralCode: string;
  applicationStatus: string;
  paymentStatus: string;
  totalReferrals: number;
  pendingRewards: number;
  paidRewards: number;
  createdAt: string;
}

export interface AdminDriversResponse {
  drivers: AdminDriverSummary[];
  total: number;
  page: number;
  limit: number;
}

export type AdminReferralRecordRewardStatus =
  (typeof AdminReferralRecordRewardStatus)[keyof typeof AdminReferralRecordRewardStatus];

export const AdminReferralRecordRewardStatus = {
  pending: "pending",
  paid: "paid",
} as const;

export interface AdminReferralRecord {
  id: number;
  referrerName: string;
  referrerEmail: string;
  referredName: string;
  referredEmail: string;
  referralNumber: number;
  rewardAmount: number;
  rewardStatus: AdminReferralRecordRewardStatus;
  qualifiedAt?: string;
  paidAt?: string;
  createdAt: string;
}

export interface AdminDriverDetail {
  driver: AdminDriverSummary;
  payment?: PaymentRecord;
  referrals: AdminReferralRecord[];
}

export interface AdminReferralsResponse {
  referrals: AdminReferralRecord[];
  total: number;
  page: number;
  limit: number;
}

export interface MarkPaidRequest {
  payoutMethod: string;
  notes?: string;
}

export interface ContactRequest {
  name: string;
  email: string;
  phone?: string;
  message: string;
}

export type AdminListDriversParams = {
  /**
   * Search by name, email, phone, or referral code
   */
  search?: string;
  /**
   * Filter by payment status
   */
  paymentStatus?: AdminListDriversPaymentStatus;
  page?: number;
  limit?: number;
};

export type AdminListDriversPaymentStatus =
  (typeof AdminListDriversPaymentStatus)[keyof typeof AdminListDriversPaymentStatus];

export const AdminListDriversPaymentStatus = {
  paid: "paid",
  pending: "pending",
  all: "all",
} as const;

export type AdminListReferralsParams = {
  rewardStatus?: AdminListReferralsRewardStatus;
  page?: number;
  limit?: number;
};

export type AdminListReferralsRewardStatus =
  (typeof AdminListReferralsRewardStatus)[keyof typeof AdminListReferralsRewardStatus];

export const AdminListReferralsRewardStatus = {
  pending: "pending",
  paid: "paid",
  all: "all",
} as const;
