/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Red Shield Founding Driver Program API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminDriverDetail,
  AdminDriversResponse,
  AdminListDriversParams,
  AdminListReferralsParams,
  AdminReferralsResponse,
  AdminStats,
  AuthResponse,
  CheckoutSessionResponse,
  ContactRequest,
  DriverDashboard,
  ErrorResponse,
  HealthStatus,
  LoginRequest,
  MarkPaidRequest,
  MessageResponse,
  PaymentStatusResponse,
  ReferralRecord,
  RegisterDriverRequest,
  UserProfile,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new driver applicant
 */
export const getRegisterDriverUrl = () => {
  return `/api/auth/register`;
};

export const registerDriver = async (
  registerDriverRequest: RegisterDriverRequest,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getRegisterDriverUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerDriverRequest),
  });
};

export const getRegisterDriverMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerDriver>>,
    TError,
    { data: BodyType<RegisterDriverRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerDriver>>,
  TError,
  { data: BodyType<RegisterDriverRequest> },
  TContext
> => {
  const mutationKey = ["registerDriver"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerDriver>>,
    { data: BodyType<RegisterDriverRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return registerDriver(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterDriverMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerDriver>>
>;
export type RegisterDriverMutationBody = BodyType<RegisterDriverRequest>;
export type RegisterDriverMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Register a new driver applicant
 */
export const useRegisterDriver = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerDriver>>,
    TError,
    { data: BodyType<RegisterDriverRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof registerDriver>>,
  TError,
  { data: BodyType<RegisterDriverRequest> },
  TContext
> => {
  return useMutation(getRegisterDriverMutationOptions(options));
};

/**
 * @summary Login as driver or admin
 */
export const getLoginUserUrl = () => {
  return `/api/auth/login`;
};

export const loginUser = async (
  loginRequest: LoginRequest,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getLoginUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginRequest),
  });
};

export const getLoginUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  const mutationKey = ["loginUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginUser>>,
    { data: BodyType<LoginRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return loginUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginUser>>
>;
export type LoginUserMutationBody = BodyType<LoginRequest>;
export type LoginUserMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Login as driver or admin
 */
export const useLoginUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  return useMutation(getLoginUserMutationOptions(options));
};

/**
 * @summary Logout current user
 */
export const getLogoutUserUrl = () => {
  return `/api/auth/logout`;
};

export const logoutUser = async (
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getLogoutUserUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutUser>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logoutUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutUser>>,
    void
  > = () => {
    return logoutUser(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutUser>>
>;

export type LogoutUserMutationError = ErrorType<unknown>;

/**
 * @summary Logout current user
 */
export const useLogoutUser = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logoutUser>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutUserMutationOptions(options));
};

/**
 * @summary Get current authenticated user
 */
export const getGetCurrentUserUrl = () => {
  return `/api/auth/me`;
};

export const getCurrentUser = async (
  options?: RequestInit,
): Promise<UserProfile> => {
  return customFetch<UserProfile>(getGetCurrentUserUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCurrentUserQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({
    signal,
  }) => getCurrentUser({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>;
export type GetCurrentUserQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current authenticated user
 */

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a Stripe checkout session for $400 joining fee
 */
export const getCreateCheckoutSessionUrl = () => {
  return `/api/payments/create-checkout`;
};

export const createCheckoutSession = async (
  options?: RequestInit,
): Promise<CheckoutSessionResponse> => {
  return customFetch<CheckoutSessionResponse>(getCreateCheckoutSessionUrl(), {
    ...options,
    method: "POST",
  });
};

export const getCreateCheckoutSessionMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCheckoutSession>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCheckoutSession>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["createCheckoutSession"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCheckoutSession>>,
    void
  > = () => {
    return createCheckoutSession(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCheckoutSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCheckoutSession>>
>;

export type CreateCheckoutSessionMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Create a Stripe checkout session for $400 joining fee
 */
export const useCreateCheckoutSession = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCheckoutSession>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createCheckoutSession>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getCreateCheckoutSessionMutationOptions(options));
};

/**
 * @summary Handle Stripe webhook events
 */
export const getStripeWebhookUrl = () => {
  return `/api/payments/webhook`;
};

export const stripeWebhook = async (
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getStripeWebhookUrl(), {
    ...options,
    method: "POST",
  });
};

export const getStripeWebhookMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof stripeWebhook>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof stripeWebhook>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["stripeWebhook"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof stripeWebhook>>,
    void
  > = () => {
    return stripeWebhook(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StripeWebhookMutationResult = NonNullable<
  Awaited<ReturnType<typeof stripeWebhook>>
>;

export type StripeWebhookMutationError = ErrorType<unknown>;

/**
 * @summary Handle Stripe webhook events
 */
export const useStripeWebhook = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof stripeWebhook>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof stripeWebhook>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getStripeWebhookMutationOptions(options));
};

/**
 * @summary Get current user's payment status
 */
export const getGetPaymentStatusUrl = () => {
  return `/api/payments/status`;
};

export const getPaymentStatus = async (
  options?: RequestInit,
): Promise<PaymentStatusResponse> => {
  return customFetch<PaymentStatusResponse>(getGetPaymentStatusUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPaymentStatusQueryKey = () => {
  return [`/api/payments/status`] as const;
};

export const getGetPaymentStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getPaymentStatus>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPaymentStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPaymentStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPaymentStatus>>
  > = ({ signal }) => getPaymentStatus({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPaymentStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPaymentStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPaymentStatus>>
>;
export type GetPaymentStatusQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current user's payment status
 */

export function useGetPaymentStatus<
  TData = Awaited<ReturnType<typeof getPaymentStatus>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPaymentStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPaymentStatusQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get driver dashboard data
 */
export const getGetDriverDashboardUrl = () => {
  return `/api/drivers/dashboard`;
};

export const getDriverDashboard = async (
  options?: RequestInit,
): Promise<DriverDashboard> => {
  return customFetch<DriverDashboard>(getGetDriverDashboardUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetDriverDashboardQueryKey = () => {
  return [`/api/drivers/dashboard`] as const;
};

export const getGetDriverDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof getDriverDashboard>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDriverDashboard>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDriverDashboardQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDriverDashboard>>
  > = ({ signal }) => getDriverDashboard({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDriverDashboard>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDriverDashboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDriverDashboard>>
>;
export type GetDriverDashboardQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get driver dashboard data
 */

export function useGetDriverDashboard<
  TData = Awaited<ReturnType<typeof getDriverDashboard>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDriverDashboard>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDriverDashboardQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get current driver's referrals
 */
export const getGetMyReferralsUrl = () => {
  return `/api/drivers/referrals`;
};

export const getMyReferrals = async (
  options?: RequestInit,
): Promise<ReferralRecord[]> => {
  return customFetch<ReferralRecord[]>(getGetMyReferralsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyReferralsQueryKey = () => {
  return [`/api/drivers/referrals`] as const;
};

export const getGetMyReferralsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyReferrals>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyReferrals>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyReferralsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyReferrals>>> = ({
    signal,
  }) => getMyReferrals({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyReferrals>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMyReferralsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyReferrals>>
>;
export type GetMyReferralsQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current driver's referrals
 */

export function useGetMyReferrals<
  TData = Awaited<ReturnType<typeof getMyReferrals>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyReferrals>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMyReferralsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Submit a contact form message
 */
export const getSubmitContactUrl = () => {
  return `/api/contact`;
};

export const submitContact = async (
  contactRequest: ContactRequest,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getSubmitContactUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactRequest),
  });
};

export const getSubmitContactMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitContact>>,
    TError,
    { data: BodyType<ContactRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitContact>>,
  TError,
  { data: BodyType<ContactRequest> },
  TContext
> => {
  const mutationKey = ["submitContact"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitContact>>,
    { data: BodyType<ContactRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return submitContact(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitContactMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitContact>>
>;
export type SubmitContactMutationBody = BodyType<ContactRequest>;
export type SubmitContactMutationError = ErrorType<unknown>;

/**
 * @summary Submit a contact form message
 */
export const useSubmitContact = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitContact>>,
    TError,
    { data: BodyType<ContactRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof submitContact>>,
  TError,
  { data: BodyType<ContactRequest> },
  TContext
> => {
  return useMutation(getSubmitContactMutationOptions(options));
};

/**
 * @summary Get overall admin stats
 */
export const getGetAdminStatsUrl = () => {
  return `/api/admin/stats`;
};

export const getAdminStats = async (
  options?: RequestInit,
): Promise<AdminStats> => {
  return customFetch<AdminStats>(getGetAdminStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAdminStatsQueryKey = () => {
  return [`/api/admin/stats`] as const;
};

export const getGetAdminStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminStats>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminStats>>> = ({
    signal,
  }) => getAdminStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAdminStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminStats>>
>;
export type GetAdminStatsQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get overall admin stats
 */

export function useGetAdminStats<
  TData = Awaited<ReturnType<typeof getAdminStats>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAdminStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all drivers with optional search
 */
export const getAdminListDriversUrl = (params?: AdminListDriversParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/admin/drivers?${stringifiedParams}`
    : `/api/admin/drivers`;
};

export const adminListDrivers = async (
  params?: AdminListDriversParams,
  options?: RequestInit,
): Promise<AdminDriversResponse> => {
  return customFetch<AdminDriversResponse>(getAdminListDriversUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getAdminListDriversQueryKey = (
  params?: AdminListDriversParams,
) => {
  return [`/api/admin/drivers`, ...(params ? [params] : [])] as const;
};

export const getAdminListDriversQueryOptions = <
  TData = Awaited<ReturnType<typeof adminListDrivers>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: AdminListDriversParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminListDrivers>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminListDriversQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminListDrivers>>
  > = ({ signal }) => adminListDrivers(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminListDrivers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminListDriversQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminListDrivers>>
>;
export type AdminListDriversQueryError = ErrorType<ErrorResponse>;

/**
 * @summary List all drivers with optional search
 */

export function useAdminListDrivers<
  TData = Awaited<ReturnType<typeof adminListDrivers>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: AdminListDriversParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminListDrivers>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAdminListDriversQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get driver detail
 */
export const getAdminGetDriverUrl = (driverId: number) => {
  return `/api/admin/drivers/${driverId}`;
};

export const adminGetDriver = async (
  driverId: number,
  options?: RequestInit,
): Promise<AdminDriverDetail> => {
  return customFetch<AdminDriverDetail>(getAdminGetDriverUrl(driverId), {
    ...options,
    method: "GET",
  });
};

export const getAdminGetDriverQueryKey = (driverId: number) => {
  return [`/api/admin/drivers/${driverId}`] as const;
};

export const getAdminGetDriverQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetDriver>>,
  TError = ErrorType<ErrorResponse>,
>(
  driverId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetDriver>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminGetDriverQueryKey(driverId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetDriver>>> = ({
    signal,
  }) => adminGetDriver(driverId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!driverId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetDriver>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetDriverQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetDriver>>
>;
export type AdminGetDriverQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get driver detail
 */

export function useAdminGetDriver<
  TData = Awaited<ReturnType<typeof adminGetDriver>>,
  TError = ErrorType<ErrorResponse>,
>(
  driverId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetDriver>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAdminGetDriverQueryOptions(driverId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all referrals
 */
export const getAdminListReferralsUrl = (params?: AdminListReferralsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/admin/referrals?${stringifiedParams}`
    : `/api/admin/referrals`;
};

export const adminListReferrals = async (
  params?: AdminListReferralsParams,
  options?: RequestInit,
): Promise<AdminReferralsResponse> => {
  return customFetch<AdminReferralsResponse>(getAdminListReferralsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getAdminListReferralsQueryKey = (
  params?: AdminListReferralsParams,
) => {
  return [`/api/admin/referrals`, ...(params ? [params] : [])] as const;
};

export const getAdminListReferralsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminListReferrals>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: AdminListReferralsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminListReferrals>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminListReferralsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminListReferrals>>
  > = ({ signal }) => adminListReferrals(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminListReferrals>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminListReferralsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminListReferrals>>
>;
export type AdminListReferralsQueryError = ErrorType<ErrorResponse>;

/**
 * @summary List all referrals
 */

export function useAdminListReferrals<
  TData = Awaited<ReturnType<typeof adminListReferrals>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: AdminListReferralsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminListReferrals>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAdminListReferralsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Mark a referral reward as paid
 */
export const getAdminMarkReferralPaidUrl = (referralId: number) => {
  return `/api/admin/referrals/${referralId}/mark-paid`;
};

export const adminMarkReferralPaid = async (
  referralId: number,
  markPaidRequest: MarkPaidRequest,
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getAdminMarkReferralPaidUrl(referralId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(markPaidRequest),
  });
};

export const getAdminMarkReferralPaidMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminMarkReferralPaid>>,
    TError,
    { referralId: number; data: BodyType<MarkPaidRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminMarkReferralPaid>>,
  TError,
  { referralId: number; data: BodyType<MarkPaidRequest> },
  TContext
> => {
  const mutationKey = ["adminMarkReferralPaid"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminMarkReferralPaid>>,
    { referralId: number; data: BodyType<MarkPaidRequest> }
  > = (props) => {
    const { referralId, data } = props ?? {};

    return adminMarkReferralPaid(referralId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminMarkReferralPaidMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminMarkReferralPaid>>
>;
export type AdminMarkReferralPaidMutationBody = BodyType<MarkPaidRequest>;
export type AdminMarkReferralPaidMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Mark a referral reward as paid
 */
export const useAdminMarkReferralPaid = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminMarkReferralPaid>>,
    TError,
    { referralId: number; data: BodyType<MarkPaidRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof adminMarkReferralPaid>>,
  TError,
  { referralId: number; data: BodyType<MarkPaidRequest> },
  TContext
> => {
  return useMutation(getAdminMarkReferralPaidMutationOptions(options));
};

/**
 * @summary Export drivers as CSV
 */
export const getAdminExportDriversUrl = () => {
  return `/api/admin/export/drivers`;
};

export const adminExportDrivers = async (
  options?: RequestInit,
): Promise<string> => {
  return customFetch<string>(getAdminExportDriversUrl(), {
    ...options,
    method: "GET",
  });
};

export const getAdminExportDriversQueryKey = () => {
  return [`/api/admin/export/drivers`] as const;
};

export const getAdminExportDriversQueryOptions = <
  TData = Awaited<ReturnType<typeof adminExportDrivers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof adminExportDrivers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminExportDriversQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminExportDrivers>>
  > = ({ signal }) => adminExportDrivers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminExportDrivers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminExportDriversQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminExportDrivers>>
>;
export type AdminExportDriversQueryError = ErrorType<unknown>;

/**
 * @summary Export drivers as CSV
 */

export function useAdminExportDrivers<
  TData = Awaited<ReturnType<typeof adminExportDrivers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof adminExportDrivers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAdminExportDriversQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Export referrals as CSV
 */
export const getAdminExportReferralsUrl = () => {
  return `/api/admin/export/referrals`;
};

export const adminExportReferrals = async (
  options?: RequestInit,
): Promise<string> => {
  return customFetch<string>(getAdminExportReferralsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getAdminExportReferralsQueryKey = () => {
  return [`/api/admin/export/referrals`] as const;
};

export const getAdminExportReferralsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminExportReferrals>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof adminExportReferrals>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminExportReferralsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminExportReferrals>>
  > = ({ signal }) => adminExportReferrals({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminExportReferrals>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminExportReferralsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminExportReferrals>>
>;
export type AdminExportReferralsQueryError = ErrorType<unknown>;

/**
 * @summary Export referrals as CSV
 */

export function useAdminExportReferrals<
  TData = Awaited<ReturnType<typeof adminExportReferrals>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof adminExportReferrals>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAdminExportReferralsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
